name:            "swc_westernarm_npz05"
park:            "swc_westernarm_npz05"
years:           [2020, 2021, 2024, 2025]
combine_benthos: TRUE
report_name:     "Project 4.21-swc_westernarm-3-Appendix C2-q-Data analysis"  # TODO
