name: "swc_westernarm"
park: "swc_westernarm"
years: ["2020", "2023", "2024", "2025"]    # EVERY survey year
combine_benthos: true       # true = pool benthos years into ONE
                             # Combine benthos if years have samples in different spatial areas
